<a href="https://colab.research.google.com/github/alinasahoo/Python/blob/main/SqlUsingPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MEDIUM BLOG = https://medium.com/jbennetcodes/how-to-rewrite-your-sql-queries-in-pandas-and-more-149d341fc53e

In [1]:
import pandas as pd

In [2]:
# Read table data
airports = pd.read_csv("/airports.csv")
airport_freq = pd.read_csv('/airport-frequencies.csv')
runways = pd.read_csv('/runways.csv') # Returns a dataframe

airports

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
0,6523,00A,heliport,Total Rf Heliport,40.070801,-74.933601,11.0,NaN,US,US-PA,Bensalem,no,00A,NaN,00A,NaN,NaN,NaN
1,323361,00AA,small_airport,Aero B Ranch Airport,38.704022,-101.473911,3435.0,NaN,US,US-KS,Leoti,no,00AA,NaN,00AA,NaN,NaN,NaN
2,6524,00AK,small_airport,Lowell Field,59.947733,-151.692524,450.0,NaN,US,US-AK,Anchor Point,no,00AK,NaN,00AK,NaN,NaN,NaN
3,6525,00AL,small_airport,Epps Airpark,34.864799,-86.770302,820.0,NaN,US,US-AL,Harvest,no,00AL,NaN,00AL,NaN,NaN,NaN
4,506791,00AN,small_airport,Katmai Lodge Airport,59.093287,-156.456699,80.0,NaN,US,US-AK,King Salmon,no,00AN,NaN,00AN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76117,46378,ZZ-0001,heliport,Sealand Helipad,51.894444,1.482500,40.0,EU,GB,GB-ENG,Sealand,no,NaN,NaN,NaN,http://www.sealandgov.org/,https://en.wikipedia.org/wiki/Principality_of_...,Roughs Tower Helipad
76118,307326,ZZ-0002,small_airport,Glorioso Islands Airstrip,-11.584278,47.296389,11.0,AF,TF,TF-U-A,Grande Glorieuse,no,NaN,NaN,NaN,NaN,NaN,NaN
76119,346788,ZZ-0003,small_airport,Fainting Goat Airport,32.110587,-97.356312,690.0,NaN,US,US-TX,Blum,no,87TX,NaN,87TX,NaN,NaN,NaN
76120,342102,ZZZW,closed,Scandium City Heliport,69.355287,-138.939310,4.0,NaN,CA,CA-YT,(Old) Scandium City,no,NaN,NaN,NaN,NaN,NaN,"ZZZW, ZZZW, ZYW, YK96"
76121,313629,ZZZZ,small_airport,Satsuma I≈çjima Airport,30.784722,130.270556,338.0,AS,JP,JP-46,Mishima,no,RJX7,NaN,RJX7,NaN,http://wikimapia.org/6705190/Satsuma-Iwo-jima-...,"SATSUMA,IWOJIMA,RJX7"

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# **SELECT / WHERE / DISTINCT/ LIMIT**

In [4]:
# SELECT * FROM Airports

airports

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
0,6523,00A,heliport,Total Rf Heliport,40.070801,-74.933601,11.0,NaN,US,US-PA,Bensalem,no,00A,NaN,00A,NaN,NaN,NaN
1,323361,00AA,small_airport,Aero B Ranch Airport,38.704022,-101.473911,3435.0,NaN,US,US-KS,Leoti,no,00AA,NaN,00AA,NaN,NaN,NaN
2,6524,00AK,small_airport,Lowell Field,59.947733,-151.692524,450.0,NaN,US,US-AK,Anchor Point,no,00AK,NaN,00AK,NaN,NaN,NaN
3,6525,00AL,small_airport,Epps Airpark,34.864799,-86.770302,820.0,NaN,US,US-AL,Harvest,no,00AL,NaN,00AL,NaN,NaN,NaN
4,506791,00AN,small_airport,Katmai Lodge Airport,59.093287,-156.456699,80.0,NaN,US,US-AK,King Salmon,no,00AN,NaN,00AN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76117,46378,ZZ-0001,heliport,Sealand Helipad,51.894444,1.482500,40.0,EU,GB,GB-ENG,Sealand,no,NaN,NaN,NaN,http://www.sealandgov.org/,https://en.wikipedia.org/wiki/Principality_of_...,Roughs Tower Helipad
76118,307326,ZZ-0002,small_airport,Glorioso Islands Airstrip,-11.584278,47.296389,11.0,AF,TF,TF-U-A,Grande Glorieuse,no,NaN,NaN,NaN,NaN,NaN,NaN
76119,346788,ZZ-0003,small_airport,Fainting Goat Airport,32.110587,-97.356312,690.0,NaN,US,US-TX,Blum,no,87TX,NaN,87TX,NaN,NaN,NaN
76120,342102,ZZZW,closed,Scandium City Heliport,69.355287,-138.939310,4.0,NaN,CA,CA-YT,(Old) Scandium City,no,NaN,NaN,NaN,NaN,NaN,"ZZZW, ZZZW, ZYW, YK96"
76121,313629,ZZZZ,small_airport,Satsuma I≈çjima Airport,30.784722,130.270556,338.0,AS,JP,JP-46,Mishima,no,RJX7,NaN,RJX7,NaN,http://wikimapia.org/6705190/Satsuma-Iwo-jima-...,"SATSUMA,IWOJIMA,RJX7"

In [5]:
# select * from airports limit 3

# airports.head(3)
airports.head() # returns 5 if no argument passed

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
0,6523,00A,heliport,Total Rf Heliport,40.070801,-74.933601,11.0,NaN,US,US-PA,Bensalem,no,00A,NaN,00A,NaN,NaN,NaN
1,323361,00AA,small_airport,Aero B Ranch Airport,38.704022,-101.473911,3435.0,NaN,US,US-KS,Leoti,no,00AA,NaN,00AA,NaN,NaN,NaN
2,6524,00AK,small_airport,Lowell Field,59.947733,-151.692524,450.0,NaN,US,US-AK,Anchor Point,no,00AK,NaN,00AK,NaN,NaN,NaN
3,6525,00AL,small_airport,Epps Airpark,34.864799,-86.770302,820.0,NaN,US,US-AL,Harvest,no,00AL,NaN,00AL,NaN,NaN,NaN
4,506791,00AN,small_airport,Katmai Lodge Airport,59.093287,-156.456699,80.0,NaN,US,US-AK,King Salmon,no,00AN,NaN,00AN,NaN,NaN,NaN

In [6]:
# select * from airports where ident = '00A'

airports[airports.ident == '00A']

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
0,6523,00A,heliport,Total Rf Heliport,40.070801,-74.933601,11.0,NaN,US,US-PA,Bensalem,no,00A,NaN,00A,NaN,NaN,NaN

In [7]:
# select id, type from airports

airports[['id', 'type']] #returns the id,type from airports

           id           type
0        6523       heliport
1      323361  small_airport
2        6524  small_airport
3        6525  small_airport
4      506791  small_airport
...       ...            ...
76117   46378       heliport
76118  307326  small_airport
76119  346788  small_airport
76120  342102         closed
76121  313629  small_airport

[76122 rows x 2 columns]

In [8]:
airports[['name','iso_country']] #returns the name, iso_country

                            name iso_country
0              Total Rf Heliport          US
1           Aero B Ranch Airport          US
2                   Lowell Field          US
3                   Epps Airpark          US
4           Katmai Lodge Airport          US
...                          ...         ...
76117            Sealand Helipad          GB
76118  Glorioso Islands Airstrip          TF
76119      Fainting Goat Airport          US
76120     Scandium City Heliport          CA
76121     Satsuma I≈çjima Airport          JP

[76122 rows x 2 columns]

In [9]:
# select id, type from airports where ident = '00AN'
# Conditions are written first
airports[airports.ident == '00AN'][['id', 'type']]

       id           type
4  506791  small_airport

In [10]:
# SELECT id,type FROM airports WHERE iso_country = 'US'

airports[airports.iso_country == 'US'][['id','type']]

           id           type
0        6523       heliport
1      323361  small_airport
2        6524  small_airport
3        6525  small_airport
4      506791  small_airport
...       ...            ...
75403   26366  small_airport
75404   26367  small_airport
75405   26368  small_airport
75911   26369  small_airport
76119  346788  small_airport

[30449 rows x 2 columns]

In [11]:
# select id from airports where ident = '00A'

airports[airports.ident == '00A'].id  # airports[airports.ident == '00AN'][['id']]

0    6523
Name: id, dtype: int64

In [12]:
# select id from airports where ident = '00A' AND name = 'Total Rf Heliport'

airports[(airports.ident == '00A') & (airports.name == 'Total Rf Heliport')].id
# for more than one conditions, we use brackets for every condition

0    6523
Name: id, dtype: int64

In [13]:
# select distinct name from airport

airports.name.unique()

array(['Total Rf Heliport', 'Aero B Ranch Airport', 'Lowell Field', ...,
       'Fainting Goat Airport', 'Scandium City Heliport',
       'Satsuma I≈çjima Airport'], dtype=object)

In [14]:
# Select Distinct Type From Airport

airports.type.unique()

array(['heliport', 'small_airport', 'closed', 'seaplane_base',
       'balloonport', 'medium_airport', 'large_airport'], dtype=object)

In [15]:
# select DISTINCT iso_country from airports where type = 'small_airport'

airports[airports.type == 'small_airport'].iso_country.unique()

array(['US', 'PR', 'MH', 'SO', 'AQ', 'PG', 'PH', 'CO', 'SD', 'SA', 'AE',
       'SS', 'CN', 'AF', 'SB', 'AU', 'MG', 'TD', 'AL', 'AM', 'MX', 'MZ',
       'PW', 'AO', 'AR', 'AT', 'GA', 'ID', 'AZ', 'BA', 'BD', 'BF', 'BG',
       'GL', 'BI', 'IS', 'BJ', 'OM', 'KE', 'BO', 'BR', 'BS', 'CV', 'BW',
       'BY', 'UA', 'LR', 'BZ', 'CA', 'GB', 'CD', 'CF', 'CG', 'CH', 'CI',
       'CL', 'CM', 'CR', 'CU', 'CY', 'CZ', 'SK', 'PA', 'DZ', 'YE', 'DE',
       'GH', 'RU', 'DJ', 'DK', 'NG', 'NE', 'TN', 'TG', 'BE', 'EC', 'EE',
       'FI', 'EG', 'EH', 'NL', 'IE', 'LU', 'NO', 'PL', 'ER', 'MN', 'ES',
       'PT', 'SE', 'ET', 'LV', 'LT', 'ZA', 'SZ', 'GQ', 'SH', 'FJ', 'FK',
       'ZM', 'FM', 'TF', 'MV', 'FR', 'SC', 'ZW', 'MW', 'LS', nan, 'ML',
       'GE', 'GF', 'SL', 'GW', 'MA', 'GN', 'SN', 'MR', 'GR', 'GT', 'TZ',
       'GU', 'GY', 'SR', 'LY', 'HN', 'VN', 'HR', 'KZ', 'RW', 'HT', 'HU',
       'UG', 'TL', 'IL', 'IM', 'IN', 'IQ', 'IR', 'IT', 'JM', 'JO', 'JP',
       'KG', 'KH', 'KP', 'KR', 'KW', 'LA', 'MY', 'LB', 'SM', 'SI', 'LK',
       'RO', 'TR', 'MK', 'RS', 'ME', 'TC', 'MD', 'DO', 'MM', 'NI', 'SV',
       'MU', 'NC', 'CK', 'TO', 'KI', 'NP', 'AS', 'WS', 'PF', 'VU', 'NZ',
       'BH', 'PK', 'SY', 'QA', 'PE', 'UM', 'PS', 'PY', 'TW', 'RE', 'SG',
       'UY', 'VE', 'AG', 'GP', 'GD', 'TH', 'TJ', 'TM', 'BQ', 'TT', 'MP',
       'VG', 'UZ', 'BT', 'BN', 'XK'], dtype=object)

In [16]:
airports[(airports.iso_region == 'US-CA') & (airports.type == 'seaplane_base')]

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
1028,7436,0O0,seaplane_base,San Luis Reservoir Seaplane Base,37.058300,-121.125999,544.0,NaN,US,US-CA,Los Banos,no,0O0,NaN,0O0,NaN,NaN,NaN
2609,8877,22CA,seaplane_base,Commodore Center Seaplane Base,37.878893,-122.512697,NaN,NaN,US,US-CA,Mill Valley,no,22CA,NaN,22CA,NaN,NaN,NaN
6567,12298,5CA9,seaplane_base,Konocti - Clear Lake Seaplane Base,38.977699,-122.718002,1326.0,NaN,US,US-CA,Kelseyville,no,5CA9,NaN,5CA9,NaN,NaN,NaN
15918,16514,C39,seaplane_base,Folsom Lake Seaplane Base,38.707199,-121.133003,466.0,NaN,US,US-CA,Folsom,no,C39,NaN,C39,NaN,NaN,NaN
18750,16830,CN20,seaplane_base,Ferndale Resort Seaplane Base,39.002998,-122.796997,1326.0,NaN,US,US-CA,Kelseyville,no,CN20,NaN,CN20,NaN,NaN,NaN
21476,17157,E20,seaplane_base,Lake Berryessa Seaplane Base,38.550979,-122.227682,440.0,NaN,US,US-CA,Napa,no,NaN,NaN,E20,NaN,NaN,NaN
27664,17613,H77,seaplane_base,Bridge Bay Resort Seaplane Base,40.757599,-122.322998,1065.0,NaN,US,US-CA,Redding,no,H77,NaN,H77,NaN,NaN,NaN
39618,21444,L11,seaplane_base,Pebbly Beach Seaplane Base,33.338402,-118.311996,NaN,NaN,US,US-CA,Avalon,no,NaN,NaN,L11,NaN,NaN,NaN
47762,23479,O06,seaplane_base,Lake Oroville Landing Area Seaplane Base,39.566601,-121.468002,900.0,NaN,US,US-CA,Oroville,no,O06,NaN,O06,NaN,NaN,NaN
52634,24384,S74,seaplane_base,Lost Isle Seaplane Base,38.004101,-121.457001,NaN,NaN,US,US-CA,Stockton,no,S74,NaN,S74,NaN,NaN,NaN
61639,300312,TWH,seaplane_base,Two Harbors Amphibious Terminal,33.432222,-118.508611,NaN,NaN,US,US-CA,Two Harbors,no,NaN,TWH,NaN,NaN,NaN,NaN
65984,342286,US-3338,seaplane_base,Avalon Port Seaplane Base,33.345260,-118.324329,NaN,NaN,US,US-CA,Avalon,no,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
# select * from airports where iso_region = 'US-CA' and type = 'seaplane_base'

airports[(airports.iso_region == 'US-CA') & (airports.type == 'seaplane_base')]
# There are braces between the two conditions, they are required

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
1028,7436,0O0,seaplane_base,San Luis Reservoir Seaplane Base,37.058300,-121.125999,544.0,NaN,US,US-CA,Los Banos,no,0O0,NaN,0O0,NaN,NaN,NaN
2609,8877,22CA,seaplane_base,Commodore Center Seaplane Base,37.878893,-122.512697,NaN,NaN,US,US-CA,Mill Valley,no,22CA,NaN,22CA,NaN,NaN,NaN
6567,12298,5CA9,seaplane_base,Konocti - Clear Lake Seaplane Base,38.977699,-122.718002,1326.0,NaN,US,US-CA,Kelseyville,no,5CA9,NaN,5CA9,NaN,NaN,NaN
15918,16514,C39,seaplane_base,Folsom Lake Seaplane Base,38.707199,-121.133003,466.0,NaN,US,US-CA,Folsom,no,C39,NaN,C39,NaN,NaN,NaN
18750,16830,CN20,seaplane_base,Ferndale Resort Seaplane Base,39.002998,-122.796997,1326.0,NaN,US,US-CA,Kelseyville,no,CN20,NaN,CN20,NaN,NaN,NaN
21476,17157,E20,seaplane_base,Lake Berryessa Seaplane Base,38.550979,-122.227682,440.0,NaN,US,US-CA,Napa,no,NaN,NaN,E20,NaN,NaN,NaN
27664,17613,H77,seaplane_base,Bridge Bay Resort Seaplane Base,40.757599,-122.322998,1065.0,NaN,US,US-CA,Redding,no,H77,NaN,H77,NaN,NaN,NaN
39618,21444,L11,seaplane_base,Pebbly Beach Seaplane Base,33.338402,-118.311996,NaN,NaN,US,US-CA,Avalon,no,NaN,NaN,L11,NaN,NaN,NaN
47762,23479,O06,seaplane_base,Lake Oroville Landing Area Seaplane Base,39.566601,-121.468002,900.0,NaN,US,US-CA,Oroville,no,O06,NaN,O06,NaN,NaN,NaN
52634,24384,S74,seaplane_base,Lost Isle Seaplane Base,38.004101,-121.457001,NaN,NaN,US,US-CA,Stockton,no,S74,NaN,S74,NaN,NaN,NaN
61639,300312,TWH,seaplane_base,Two Harbors Amphibious Terminal,33.432222,-118.508611,NaN,NaN,US,US-CA,Two Harbors,no,NaN,TWH,NaN,NaN,NaN,NaN
65984,342286,US-3338,seaplane_base,Avalon Port Seaplane Base,33.345260,-118.324329,NaN,NaN,US,US-CA,Avalon,no,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# select ident, name, municipality from airports where iso_region = 'US-CA' and type = 'seaplane_base'

airports[(airports.iso_region == 'US-CA') & (airports.type == 'seaplane_base')][['ident','name','municipality']]

         ident                                      name municipality
1028       0O0          San Luis Reservoir Seaplane Base    Los Banos
2609      22CA            Commodore Center Seaplane Base  Mill Valley
6567      5CA9       Konocti  - Clear Lake Seaplane Base  Kelseyville
15918      C39                 Folsom Lake Seaplane Base       Folsom
18750     CN20             Ferndale Resort Seaplane Base  Kelseyville
21476      E20              Lake Berryessa Seaplane Base         Napa
27664      H77           Bridge Bay Resort Seaplane Base      Redding
39618      L11                Pebbly Beach Seaplane Base       Avalon
47762      O06  Lake Oroville Landing Area Seaplane Base     Oroville
52634      S74                   Lost Isle Seaplane Base     Stockton
61639      TWH           Two Harbors Amphibious Terminal  Two Harbors
65984  US-3338                 Avalon Port Seaplane Base       Avalon

WHERE CLUASE - Table_Name[CONDITIONS With & / | < > != ==].column_name or multiple column [['col_1' , 'col_2_name']]

# **ORDER BY ASC / DESC**

In [19]:
# select * from airport_freq where airport_ident = 'KLAX' order by type

airport_freq[airport_freq.airport_ident == 'KLAX'].sort_values('type') # by default, it sorts in the ascending order

          id  airport_ref airport_ident  type description  frequency_mhz
12151  60767         3632          KLAX   APP   SOCAL APP          36.07
12152  60766         3632          KLAX   APP   SOCAL APP         124.30
12153  60768         3632          KLAX  ATIS        ATIS         133.80
12154  60769         3632          KLAX   CLD    CLNC DEL         121.40
12155  60770         3632          KLAX   DEP   SOCAL DEP         124.30
12156  60771         3632          KLAX   GND         GND         121.65
12157  60772         3632          KLAX  MISC          CG          34.50
12158  60773         3632          KLAX  MISC          CG         898.40
12159  60774         3632          KLAX   OPS          AF          37.22
12160  60775         3632          KLAX   TWR         TWR         119.80
12161  60776         3632          KLAX  UNIC      UNICOM         122.95

In [20]:
# select * from airport_freq where airport_ident = 'KLAX' order by airport_ident ASC frequency_mhz desc

airport_freq[airport_freq.airport_ident == 'KLAX'].sort_values(['airport_ident', 'frequency_mhz'], ascending =[True, False])

          id  airport_ref airport_ident  type description  frequency_mhz
12158  60773         3632          KLAX  MISC          CG         898.40
12153  60768         3632          KLAX  ATIS        ATIS         133.80
12152  60766         3632          KLAX   APP   SOCAL APP         124.30
12155  60770         3632          KLAX   DEP   SOCAL DEP         124.30
12161  60776         3632          KLAX  UNIC      UNICOM         122.95
12156  60771         3632          KLAX   GND         GND         121.65
12154  60769         3632          KLAX   CLD    CLNC DEL         121.40
12160  60775         3632          KLAX   TWR         TWR         119.80
12159  60774         3632          KLAX   OPS          AF          37.22
12151  60767         3632          KLAX   APP   SOCAL APP          36.07
12157  60772         3632          KLAX  MISC          CG          34.50

# **IN / NOT IN**

In [21]:
# select * from airports where type in ('heliport', 'balloonport')

airports[airports.type.isin(['heliport', 'balloonport'])]

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
0,6523,00A,heliport,Total Rf Heliport,40.070801,-74.933601,11.0,NaN,US,US-PA,Bensalem,no,00A,NaN,00A,NaN,NaN,NaN
10,322658,00CN,heliport,Kitchen Creek Helibase Heliport,32.727374,-116.459742,3350.0,NaN,US,US-CA,Pine Valley,no,00CN,NaN,00CN,NaN,NaN,NaN
16,6535,00GE,heliport,Caffrey Heliport,33.887982,-84.736983,957.0,NaN,US,US-GA,Hiram,no,00GE,NaN,00GE,NaN,NaN,NaN
17,6536,00HI,heliport,Kaupulehu Heliport,19.832881,-155.978347,43.0,OC,US,US-HI,Kailua-Kona,no,00HI,NaN,00HI,NaN,NaN,NaN
22,6540,00IN,heliport,St Mary Medical Center Heliport,41.511398,-87.260597,634.0,NaN,US,US-IN,Hobart,no,00IN,NaN,00IN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76059,351677,ZW-0055,heliport,Elephant Hills Heliport,-17.911990,25.828020,3054.0,AF,ZW,ZW-MN,Victoria Falls,no,NaN,NaN,NaN,NaN,NaN,NaN
76060,351678,ZW-0056,heliport,Chikopokopo Heliport,-17.964380,25.809930,3012.0,AF,ZW,ZW-MN,Masuwe,no,NaN,NaN,NaN,NaN,NaN,NaN
76061,351679,ZW-0057,heliport,Masuwe Heliport,-17.965880,25.810550,3005.0,AF,ZW,ZW-MN,Masuwe,no,NaN,NaN,NaN,NaN,NaN,NaN
76063,351689,ZW-0059,heliport,Big Four Heliport,-17.913540,25.832350,2986.0,AF,ZW,ZW-MN,Victoria Falls,no,NaN,NaN,NaN,NaN,NaN,NaN
76117,46378,ZZ-0001,heliport,Sealand Helipad,51.894444,1.482500,40.0,EU,GB,GB-ENG,Sealand,no,NaN,NaN,NaN,http://www.sealandgov.org/,https://en.wikipedia.org/wiki/Principality_of_...,Roughs Tower Helipad

In [22]:
# select * from airports where type in ('heliport', 'balloonport')

airports[(airports.type == 'heliport') | (airports.type == 'balloonport')]

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
0,6523,00A,heliport,Total Rf Heliport,40.070801,-74.933601,11.0,NaN,US,US-PA,Bensalem,no,00A,NaN,00A,NaN,NaN,NaN
10,322658,00CN,heliport,Kitchen Creek Helibase Heliport,32.727374,-116.459742,3350.0,NaN,US,US-CA,Pine Valley,no,00CN,NaN,00CN,NaN,NaN,NaN
16,6535,00GE,heliport,Caffrey Heliport,33.887982,-84.736983,957.0,NaN,US,US-GA,Hiram,no,00GE,NaN,00GE,NaN,NaN,NaN
17,6536,00HI,heliport,Kaupulehu Heliport,19.832881,-155.978347,43.0,OC,US,US-HI,Kailua-Kona,no,00HI,NaN,00HI,NaN,NaN,NaN
22,6540,00IN,heliport,St Mary Medical Center Heliport,41.511398,-87.260597,634.0,NaN,US,US-IN,Hobart,no,00IN,NaN,00IN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76059,351677,ZW-0055,heliport,Elephant Hills Heliport,-17.911990,25.828020,3054.0,AF,ZW,ZW-MN,Victoria Falls,no,NaN,NaN,NaN,NaN,NaN,NaN
76060,351678,ZW-0056,heliport,Chikopokopo Heliport,-17.964380,25.809930,3012.0,AF,ZW,ZW-MN,Masuwe,no,NaN,NaN,NaN,NaN,NaN,NaN
76061,351679,ZW-0057,heliport,Masuwe Heliport,-17.965880,25.810550,3005.0,AF,ZW,ZW-MN,Masuwe,no,NaN,NaN,NaN,NaN,NaN,NaN
76063,351689,ZW-0059,heliport,Big Four Heliport,-17.913540,25.832350,2986.0,AF,ZW,ZW-MN,Victoria Falls,no,NaN,NaN,NaN,NaN,NaN,NaN
76117,46378,ZZ-0001,heliport,Sealand Helipad,51.894444,1.482500,40.0,EU,GB,GB-ENG,Sealand,no,NaN,NaN,NaN,http://www.sealandgov.org/,https://en.wikipedia.org/wiki/Principality_of_...,Roughs Tower Helipad

In [23]:
# select * from airports where type not in ('heliport', 'balloonport')

airports[~airports.type.isin(['heliport', 'balloonport'])] # Notice the tilde at the start

airports[~airports.type.isin(['heliport', 'balloonport'])]

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
1,323361,00AA,small_airport,Aero B Ranch Airport,38.704022,-101.473911,3435.0,NaN,US,US-KS,Leoti,no,00AA,NaN,00AA,NaN,NaN,NaN
2,6524,00AK,small_airport,Lowell Field,59.947733,-151.692524,450.0,NaN,US,US-AK,Anchor Point,no,00AK,NaN,00AK,NaN,NaN,NaN
3,6525,00AL,small_airport,Epps Airpark,34.864799,-86.770302,820.0,NaN,US,US-AL,Harvest,no,00AL,NaN,00AL,NaN,NaN,NaN
4,506791,00AN,small_airport,Katmai Lodge Airport,59.093287,-156.456699,80.0,NaN,US,US-AK,King Salmon,no,00AN,NaN,00AN,NaN,NaN,NaN
5,6526,00AR,closed,Newport Hospital & Clinic Heliport,35.608700,-91.254898,237.0,NaN,US,US-AR,Newport,no,NaN,NaN,NaN,NaN,NaN,00AR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76116,32753,ZYYY,medium_airport,Shenyang Dongta Airport,41.784401,123.496002,NaN,AS,CN,CN-21,"Dadong, Shenyang",no,ZYYY,NaN,NaN,NaN,NaN,NaN
76118,307326,ZZ-0002,small_airport,Glorioso Islands Airstrip,-11.584278,47.296389,11.0,AF,TF,TF-U-A,Grande Glorieuse,no,NaN,NaN,NaN,NaN,NaN,NaN
76119,346788,ZZ-0003,small_airport,Fainting Goat Airport,32.110587,-97.356312,690.0,NaN,US,US-TX,Blum,no,87TX,NaN,87TX,NaN,NaN,NaN
76120,342102,ZZZW,closed,Scandium City Heliport,69.355287,-138.939310,4.0,NaN,CA,CA-YT,(Old) Scandium City,no,NaN,NaN,NaN,NaN,NaN,"ZZZW, ZZZW, ZYW, YK96"
76121,313629,ZZZZ,small_airport,Satsuma I≈çjima Airport,30.784722,130.270556,338.0,AS,JP,JP-46,Mishima,no,RJX7,NaN,RJX7,NaN,http://wikimapia.org/6705190/Satsuma-Iwo-jima-...,"SATSUMA,IWOJIMA,RJX7"

# **GROUP BY / COUNT / ORDER BY**

In [24]:
# select type, count(id) from airports group by type

airports.groupby('type').agg(count_column=('id', 'count')) # .agg(name_of_col=('on_which_col_is_agg_applied', 'name_of_agg'))

# select type, count(id) from airports group by type having count(*) > 100

x = airports.groupby('type').agg(count_column=('id', 'count'))
# GROUP BY, HAVING - in a diff step

y = x[x.count_column > 100]

# select type, count(id) from airports group by type having count(*) > 100 ORDER BY count_column DESC, type ASC

z = y.sort_values(['count_column', 'type'], ascending=[False, True])

z

# GROUP BY, HAVING, ORDER

# airports.set_index('id')

# count  = total no of non null values
# size = total no of values including missing or null values,
# min
# max
# sum

# Use size when you need to know the total number of elements, including missing or null values,
# and use count when you need to know the number of non-null values in your data

                count_column
type
small_airport          39712
heliport               19364
closed                 10624
medium_airport          4751
seaplane_base           1157
large_airport            465

In [25]:
# select iso_country, type, count(*) from airports group by iso_country, type order by iso_country, type

# airports.groupby(['iso_country', 'type']).agg(count_column=('id', 'count'))

airports.groupby(['iso_country', 'type']).size() # This returns a series # DON"T READ THIS

iso_country  type
AD           closed              1
             heliport            2
AE           closed              3
             heliport          200
             large_airport       4
                              ...
ZW           closed              6
             heliport            5
             large_airport       1
             medium_airport      8
             small_airport     135
Length: 978, dtype: int64

In [26]:
# select iso_country, type, count(*) from airports group by iso_country, type order by iso_country, count(*) desc

airports.groupby(['iso_country', 'type']).agg(count=('iso_country', 'count')).sort_values(['iso_country', 'count'], ascending=[True, False]).reset_index()

    iso_country            type  count
0            AD        heliport      2
1            AD          closed      1
2            AE        heliport    200
3            AE   small_airport     31
4            AE  medium_airport      8
..          ...             ...    ...
973          ZW   small_airport    135
974          ZW  medium_airport      8
975          ZW          closed      6
976          ZW        heliport      5
977          ZW   large_airport      1

[978 rows x 3 columns]

# **HAVING**

In [27]:
tab = {'name': ["A", "B", "C", "D"],
       'age': [10, 20, 30, 16],
       'salary': [1000, 20000, 9500, 7000],
       'dept': ['IT', 'IT', 'Sales', 'Marketing']}

df = pd.DataFrame(tab)

# select min(age), max(salary), dept FROM Emp GROUP by dept
df.groupby('dept').agg(min_age=('age', 'min'), max_salary=('salary', 'max'))
# We can write having in the next step

           min_age  max_salary
dept
IT              10       20000
Marketing       16        7000
Sales           30        9500

In [28]:
# SELECT dept, min_age, max_salary from Employee GROUP BY dept HAVING MIN(age) < 20 AND max_salary > 6000

# GROUP BY ke baad sab ek alag table mai likhlo fir .reset_index() karo fir apply filtering, sorting and limit.

df.reset_index() # Brings everything to same level

a = df.groupby('dept').agg(min_age=('age','min'), max_salary=('salary', 'max'))

a[(a.min_age < 20) & (a.max_salary > 6000)].reset_index()

        dept  min_age  max_salary
0         IT       10       20000
1  Marketing       16        7000

# **TOP N RECORDS**

In [29]:
tab = {'name': ["A", "B", "C", "D"], 'age': [10, 20, 10, 16], 'salary': [1000, 20000, 9500, 7000], 'dept': ['IT', 'IT', 'Sales', 'Marketing']}
df = pd.DataFrame(tab)

df.nlargest(2, columns=['age', 'salary']) # ORDER BY age DESC salary DESC LIMIT 2

  name  age  salary       dept
1    B   20   20000         IT
3    D   16    7000  Marketing

In [30]:
tab = {'name': ["A", "B", "C", "D"], 'age': [10, 20, 10, 16], 'salary': [1000, 20000, 9500, 7000], 'dept': ['IT', 'IT', 'Sales', 'Marketing']}
df = pd.DataFrame(tab)

df.nsmallest(2, columns=['age']) # ORDER BY age ASC LIMIT 2

  name  age  salary   dept
0    A   10    1000     IT
2    C   10    9500  Sales

In [31]:
df.sort_values('salary', ascending=True).iloc[2:] # ORDER BY LIMIT AND OFFSET # REMEMBER ONLY THIS

# df.sort_values(['salary', 'name'], ascending=[True, False]).iloc[2:]

  name  age  salary   dept
2    C   10    9500  Sales
1    B   20   20000     IT

# **Aggregate functions (MIN, MAX, MEAN)**

In [32]:
tab = {'name': ["A", "B", "C", "D", "E"],
       'age': [10, 20, 10, 16, 70],
       'salary': [4000, 20000, 9500, 7000, 1000],
       'dept': ['IT', 'IT', 'Sales', 'Marketing', 'Marketing']}
df = pd.DataFrame(tab)

df.groupby('dept').agg(min_age=('age', 'min'), max_salary=('salary', 'max')).reset_index()

# MEDIAN, AVERAGE / MEAN, MAX, MIN, SUM all function are there
# https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.SeriesGroupBy.aggregate.html

        dept  min_age  max_salary
0         IT       10       20000
1  Marketing       16        7000
2      Sales       10        9500

# **JOIN**

In [33]:
emp = {'id': [10, 20, 30, 40, 50, 70],
       'name': ["A", "B", "C", "D", "E", 'G'],
       'age': [10, 20, 10, 16, 70, 102],
       'dept': ['IT', 'IT', 'Sales', 'Marketing', 'Marketing', 'Sales']}
emp_df = pd.DataFrame(emp)

sal = {'id': [10, 20, 30, 40, 50, 60],
       'name': ["A", "B", "C", "D", "E", "F"],
       'salary': [1000, 2000, 3000, 10000, 100, 1500]}
sal_df = pd.DataFrame(sal)

# df1.merge(df2)

# select id, name, dept, salary FROM emp JOIN sal ON emp.id = sal.id WHERE age > 10 AND sal > 100

# A JOIN B ON a.col1 = B.col2 left_on = 'col1', right_on='col2'
# A JOIN B ON a.col = B.col left_on = 'col', right_on='col' OR on='col'
# how = inner, outer, left, right
emp_df[emp_df.age > 10].merge(sal_df[sal_df.salary > 100], left_on='id', right_on='id', how='outer')[['id', 'name_x', 'dept', 'salary']]

   id name_x       dept   salary
0  20      B         IT   2000.0
1  40      D  Marketing  10000.0
2  50      E  Marketing      NaN
3  70      G      Sales      NaN
4  10    NaN        NaN   1000.0
5  30    NaN        NaN   3000.0
6  60    NaN        NaN   1500.0

In [34]:
import pandas as pd
# A JOIN B ON a.col1 = B.col AND a.col2 = b.col2 =====> 2 left_on = ['col1', 'col2], right_on='col2'

df = pd.DataFrame({'Courses': ["Spark","PySpark","Python","pandas","Java"],
                    'Fee' : [20000,25000,30000,24000,40000],
                    'Duration':['30day','40days','60days','55days','50days']})

df1 = pd.DataFrame({'Courses': ["Java","PySpark","Python","pandas","Hyperion"],
                    'Fee': [20000,25000,30000,24000,40000],
                    'Percentage':['10%','20%','25%','20%','10%']})

# Merge multiple columns
# Use pandas.merge() on multiple columns
df2 = pd.merge(df, df1, on=['Courses','Fee']) # Same column names on both sides, if column name is different then use left_on, and right_on
print(df2)

# It is hard to do no non - equi joins in pandas. You need to filter after normal join in order to support that.
# https://stackoverflow.com/questions/50573457/pandas-equivalent-of-sql-non-equi-join

   Courses    Fee Duration Percentage
0  PySpark  25000   40days        20%
1   Python  30000   60days        25%
2   pandas  24000   55days        20%

In [35]:
emp = {'id': [10, 20, 30, 40, 50, 70],
       'name': ["A", "B", "C", "D", "E", 'G'],
       'age': [10, 20, 10, 16, 70, 102],
       'dept': ['IT', 'IT', 'Sales', 'Marketing', 'Marketing', 'Sales']}
emp_df = pd.DataFrame(emp)

emp_2 = {'id': [10, 10, 20, 20, 30, 30], 'class': ['1st', '2nd', '3rd', '4th', '5th', '6th']}
emp_2_df = pd.DataFrame(emp_2)

emp_df.merge(emp_2_df)

# Self join, inner, outer, left, right everything can be done

   id name  age   dept class
0  10    A   10     IT   1st
1  10    A   10     IT   2nd
2  20    B   20     IT   3rd
3  20    B   20     IT   4th
4  30    C   10  Sales   5th
5  30    C   10  Sales   6th

# **UNION / UNION ALL**

In [36]:
emp_1 = {'id': [10, 20, 30, 40, 50, 70],
       'name': ["A", "B", "C", "D", "E", 'G']}
emp_1_df = pd.DataFrame(emp_1)

emp_2 = {'id': [10, 20, 33, 43, 53, 73],
       'name': ["A", "B", "H", "I", "J", 'L']}
emp_2_df = pd.DataFrame(emp_2)

pd.concat([emp_1_df, emp_2_df]) # UNION

   id name
0  10    A
1  20    B
2  30    C
3  40    D
4  50    E
5  70    G
0  10    A
1  20    B
2  33    H
3  43    I
4  53    J
5  73    L

In [37]:
emp_1 = {'id': [10, 20, 30, 40, 50, 70],
       'name': ["A", "B", "C", "D", "E", 'G']}
emp_1_df = pd.DataFrame(emp_1)

emp_2 = {'id': [10, 20, 33, 43, 53, 73],
       'name': ["A", "B", "H", "I", "J", 'L']}
emp_2_df = pd.DataFrame(emp_2)

pd.concat([emp_1_df, emp_2_df]).drop_duplicates() # UNION ALL
# To deduplicate things (equivalent of UNION), you‚Äôd also have to add .drop_duplicates().

   id name
0  10    A
1  20    B
2  30    C
3  40    D
4  50    E
5  70    G
2  33    H
3  43    I
4  53    J
5  73    L

# **CREATE TABLE / INSERT / UPDATE / DELETE**

In [38]:
# CREATE TABLE Emp
# insert into Emp values (10, 'A')
# insert into Emp values (20, 'B')
# insert into Emp values (30, 'C')

emp = {'id': [10, 20, 30],
       'name': ["A", "B", "C"]}
emp_df = pd.DataFrame(emp) # Table is made

# After some time let's say we want to add do another 'insert into Emp values (40, 'D')'

emp_2 = {'id': [40], 'name':['D']}
emp_2_df = pd.DataFrame(emp_2)

emp = pd.concat([emp_df, emp_2_df])

emp_df

   id name
0  10    A
1  20    B
2  30    C

In [39]:
# UPDATE Emp SET name = 'AAAA' WHERE id = 10 AND name = 'A'

emp_df.loc[(emp_df.id == 10) & (emp_df.name == 'A'), 'name'] = 'AAAA' # Happens in place

emp_df

   id  name
0  10  AAAA
1  20     B
2  30     C

In [40]:
# DELETE FROM Emp WHERE id = 10 AND name = 'A'

emp_df.drop(emp_df[(emp_df.id == 10) & (emp_df.name == 'AAAA')].index)

   id name
1  20    B
2  30    C

#**By default, most operators applied to a Pandas dataframe return a new object. Some operators accept a parameter inplace=True, so you can work with the original dataframe instead.**

# **PARTITION AND OVER**

In [41]:
emp = {'id': [10, 20, 30, 40, 50, 70],
       'name': ["A", "B", "C", "D", "E", 'G'],
       'age': [10, 20, 10, 16, 70, 102],
       'dept': ['IT', 'IT', 'IT', 'Marketing', 'Marketing', 'Sales']}
emp_df = pd.DataFrame(emp)

emp_df['rank'] = emp_df.groupby('dept')['age'].rank(method='dense', ascending=False) # method='first' is also there, which acts like row_num
emp_df
# Using this we can solve highest in each group, top 5 in each group questions

   id name  age       dept  rank
0  10    A   10         IT   2.0
1  20    B   20         IT   1.0
2  30    C   10         IT   2.0
3  40    D   16  Marketing   2.0
4  50    E   70  Marketing   1.0
5  70    G  102      Sales   1.0